### PR TITLE
Runtime translations and config stuff

### PR DESCRIPTION
**Pull request by YTG1234**
~~This will eventually expand to other resource pack / data pack entries. Translations are just the start.~~

~~This is of course a draft as the branch is not complete.~~

**Update**
This is not only ARRP now, I also added config validation. Why? Yes.

### CODE REVIEW

**Comment by YTG1234** [comment]
This seems to mostly work and be stable. I want to get this merged as soon as possible, I'll do other translations after that.

**Comment by YTG1234** [comment]
Any objections before I merge?

**Comment by TropheusJ** [comment]
If it launches it's good enough for me :)

**Comment by YTG1234** [comment]
It launches, translations work. I don't know if I broke existing features though - I've not been following the progress and so I don't know how to test those.

**Comment by YTG1234** [comment]
I'll merge in 5 minutes

**Pull request merged**
